db.ingredients.insertMany([
    { name: "Alface" },
    
    { name: "Leite" },
    { name: "Ovo" },
    { name: "Manteiga" },
    { name: "Creme de Leite" },
    { name: "Leite Condensado" },
    { name: "Queijo" },
    { name: "Iogurte" },
    { name: "Maionese" },
    { name: "Requeijão" },

    { name: "Essência de Baunilha" },
    { name: "Chocolate" },
    { name: "Noz Moscada" },
    { name: "Cravo" },
   
    { name: "Pão" },
    
    { name: "Mel" },
    { name: "Chá" },
    
    { name: "Molho de Tomate" },
    { name: "Alho" },
    { name: "Óleo" },

    { name: "Aveia" },
    { name: "Farinha" },
    { name: "Fermento" },
    { name: "Amido de Milho" },
    { name: "Leite em Pó" },
    { name: "Café em Pó" },
    { name: "Chocolate em Pó" },
    { name: "Canela em Pó" },
    { name: "Cacau em Pó" },
    { name: "Bicarbonato de Sódio" },
    { name: "Tapioca" },
    
    { name: "Frango" },
    { name: "Presunto" },

    { name: "Tomate" },
    { name: "Morango" },
    { name: "Melão" },
    { name: "Limão" },
    { name: "Mamão" },
    { name: "Maçã" },
    { name: "Banana" },
    { name: "Laranja" },
    { name: "Coco" },
]);

db.recipes.insertMany([
    {
        name: "Ovos mexidos",
        description: "Ovos mexidos de café da manhã são uma opção ótima para te dar aquele gostinho de café da amanhã de hotel. <br><br>Ingredientes:<br>4 ovos<br>1 colher (sopa) de manteiga<br><br>Modo de preparo:<br>Passe toda a manteiga no fundo de uma frigideira e coloque os ovos sobre a manteiga. <br>Em seguida, quebre as gemas sem mexer os ovos. <br>Leve a frigideira para o fogo com fogo baixo. <br> Seus ovos mexidos logo ficarão prontos!",
        cuisine: "brasileira",
        type_of: 1,
        image: "https://images.pexels.com/photos/8055161/pexels-photo-8055161.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        ingredients: ["Ovo", "Manteiga"],
        difficulty: "fácil",
        restriction: ["vegano", "laticinio"]
    },
    {
        name: "Waffles",
        description: "Ele é delicioso, perfeito para o café da manhã e as crianças adoram!<br><br>Ingredientes:<br>2 xícaras (chá) de farinha de trigo<br>2 colher (sopa) de açúcar<br>2 colheres (chá) de fermento em pó<br>1/2 colher (chá) de sal<br>2 colheres amido de milho<br>3 ovos batidos<br>4 colheres (sopa) de manteiga sem sal derretida<br>1 e 3/4 de xícara (chá) de leite<br>1 colher (sopa) de essência de baunilha<br><br>Modo de preparo:<br>Peneire em um recipiente a farinha de trigo, o açúcar, o amido, o fermento e o sal. Reserve.<br>Em outro recipiente misture os ovos batidos com o leite, a manteiga derretida e a essência de baunilha.<br>Despeje sobre a mistura de farinha e rapidamente incorpore os ingredientes.<br>Aqueça o aparelho para Waffles. Coloque uma concha rasa de massa e espalhe até cobrir o molde do aparelho, feche a tampa e deixe assar até a massa ficar bem dourada.<br>Retire com espátulas de silicone. Sirva com mel, frutas ou geleia.",
        cuisine: "americana",
        type_of: 1,
        image: "https://images.pexels.com/photos/4963802/pexels-photo-4963802.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        ingredients: ["Farinha", "Fermento", "Amido de Milho", "Manteiga", "Essência de Baunilha", "Ovo", "Leite"],
        difficulty: "médio",
        restriction: ["gluten", "vegano", "laticinio"],
    },
    {
        name: "Salada de frutas",
        description: "Fresquinha e pronta para saborear! Imagine uma mistura colorida de frutas frescas e suculentas.<br><br>Ingredientes:<br>1/2 mamão picadinho<br>1/2 melão picadinho<br>1 maçã grande com casca picadinha<br>2 bananas em rodelas e depois cortadas ao meio<br>Suco de 3 laranjas<br><br>Modo de preparo:<br>Misture todas as frutas com o suco de laranja (exceto a banana).<br>Coloque a banana apenas na hora de servir a salada, pois ela fica estraga facilmente, comprometendo todo o gosto da salada.<br>Se desejar acrescente manga e abacaxi picadinhos.",
        cuisine: "brasileira",
        type_of: 1,
        image: "https://images.pexels.com/photos/6331131/pexels-photo-6331131.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        ingredients: ["Melão", "Mamão", "Maçã", "Banana", "Laranja"],
        difficulty: "fácil",
        restriction: [],
    },
    {
        name: "Vitamina de banana",
        description: "Uma explosão de sabor e energia em um copo! A suavidade cremosa da banana misturada com o frescor do leite gelado e uma pitada de doçura natural.<br><br>Ingredientes:<br>5 bananas<br>1 litro de leite<br>Açúcar a gosto<br>Gelo a gosto<br><br>Modo de preparo:<br>Coloque todos os ingredientes dentro do liquidificador e bata por cerca de 2 minutos.",
        cuisine: "brasileira",
        type_of: 1,
        image: "https://images.pexels.com/photos/4112870/pexels-photo-4112870.png?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        ingredients: ["Leite", "Banana"],
        difficulty: "fácil",
        restriction: ["laticinio", "vegano"],
    },
    {
        name: "Cappuccino cremoso",
        description: "Uma xícara fria cheia de café forte, leite bem cremoso e uma camada espumosa por cima.<br><br>Ingredientes:<br>8 pedras de gelo<br>1 caixinha de creme de leite (se possível gelada)<br>3 colheres de leite em pó<br>200 ml de leite gelado<br>3 colheres (sopa) cheias de café em pó<br>Só use açúcar se gostar de um pouquinho mais doce<br><br>Modo de preparo:<br>Bata bem todos os ingredientes no liquidificador. Pronto, é só servir!",
        cuisine: "italiana",
        type_of: 1,
        image: "https://images.pexels.com/photos/302904/pexels-photo-302904.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        ingredients: ["Creme de Leite", "Leite em Pó", "Leite", "Café em Pó"],
        difficulty: "fácil",
        restriction: ["laticinio", "vegano"],
    },
    {
        name: "Cookies",
        description: "Uma explosão de sabor em cada mordida! Uma bandeja quente, saindo do forno, repleta de cookies dourados por fora e macios por dentro.<br><br>Ingredientes:<br>125 g de manteiga sem sal em temperatura ambiente<br>3/4 xícara de açúcar<br>1/2 xícara de açúcar mascavo<br>1 ovo<br>1 e 3/4 de xícara de farinha de trigo<br>1 colher (chá) de fermento em pó<br>300 g de chocolate meio amargo picado<br>1 colher (chá) de essência de baunilha<br>Para fazer cookie de chocolate acrescentar 1/4 xícara de chocolate em pó<br><br>Modo de preparo:<br>Misture a manteiga, açúcar mascavo, açúcar, essência de baunilha (e chocolate em pó, se for fazer cookies com base de chocolate).<br>Adicione o ovo batido aos poucos e misture bem.<br>Acrescente a farinha aos poucos e misture bem (pode ser na mão ou na batedeira).<br>Por último, adicione o fermento e misture só para incorporá-lo à massa.<br>Depois da massa bem misturada, adicione o chocolate picado.<br>Forme bolinhas pequenas e asse em forno pré aquecido, sobre papel manteiga, por aproximadamente 15 a 20 minutos (250° C).",
        cuisine: "americana",
        type_of: 1,
        image: "https://images.pexels.com/photos/189536/pexels-photo-189536.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        ingredients: ["Manteiga", "Ovo","Farinha","Fermento","Essência de Baunilha","Chocolate em Pó","Chocolate"],
        difficulty: "médio",
        restriction: ["vegano", "gluten", "laticinio"],
    },
    {
        name: "Torrada",
        description: "Prontas para serem saboreadas a qualquer momento do dia! Imagine fatias douradas de pão recém-torrado, crocantes por fora e macias por dentro.<br><br>Ingredientes:<br>2 colheres (sopa) de manteiga<br>1 colher (sopa) de óleo<br>1 colher (sopa) de queijo parmesão ralado<br>1/2 colher (sopa) de orégano<br>1 pitada de sal<br>Pães franceses secos cortados em rodelas<br><br>Modo de preparo:<br>Misture todos os ingredientes com uma colher em uma vasilha média.<br>Passe o tempero nas rodelas do pão.<br>Acomode as rodelas em uma assadeira (sem untar) e leve ao forno médio, até perceber que o tempero está douradinho.<br>Sirva em seguida.",
        cuisine: "brasileira",
        type_of: 1,
        image: "https://images.pexels.com/photos/19740636/pexels-photo-19740636/free-photo-of-placa-prato-torrada-brinde.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        ingredients: ["Manteiga", "Óleo", "Queijo", "Pão"],
        difficulty: "fácil",
        restriction: ["gluten", "laticinio" , "vegano"],
    },
    {
        name: "Bolacha de mel",
        description: "Uma combinação irresistível de doçura e crocância! Imagine uma bolacha dourada e delicadamente crocante, perfumada com o aroma reconfortante do mel puro.<br><br>Ingredientes:<br>400 g de mel<br>250 g de açúcar<br>250 g de manteiga<br>3 ovos<br>1 colher de sopa de cravo moído<br>1 colher de sopa de canela em pó <br>1 colher de sopa de noz moscada ralada<br>1/2 colher de sopa de fermento em pó<br>1/2 colher de sopa de bicarbonato de sódio<br>1 kg de farinha de trigo<br><br>Modo de preparo:<br>Misture o mel, o açúcar e a manteiga e leve ao fogo até misturar bem, não deixe ferver, desligue o fogo, coloque em uma bacia, acrescente os temperos e os outros ingredientes, a massa vai ficar firme, mas não dura.<br>Pode até grudar um pouco nas mãos, reparte em dois,coloque em saquinhos de plástico e leve para gelar.<br>Use um rolo para abrir, estique a massa entre dois plastico, não deixe a massa muito fina, mais ou menos 0,5 cm.<br>Corte no formato desejado, pode ser usado cortadores.<br>Leve para assar em forno quente por 10 minutos, deixe esfriar e decore como quiser.",
        cuisine: "brasileira",
        type_of: 1,
        image: "https://images.pexels.com/photos/5618150/pexels-photo-5618150.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        ingredients: ["Mel", "Manteiga", "Ovo", "Cravo", "Canela em Pó", "Noz Moscada", "Fermento", "Farinha", "Bicarbonato de Sódio"],
        difficulty: "difícil",
        restriction: ["gluten", "vegano", "laticinio"],
    },
    {
        name: "Mingau de cacau",
        description: "Uma opção saudável e super nutritiva para o café da manhã, sem amido de milho e sem açúcar.<br><br>Ingredientes:<br>2 colheres (sopa) farelo de aveia<br>150 ml de leite<br>1 colher (sopa) de cacau em pó<br>Adoçante líquido a gosto, opcional<br><br>Modo de preparo:<br>Dentro de um recipiente, coloque o farelo de aveia, o cacau e 50 ml de leite. Misture bem<br>Deixe descansar por aproximadamente 5 minutos<br>Em seguida, coloque o restante do leite dentro de uma panela, junte a aveia hidratada e misture bem<br>Leve ao fogo baixo e mexa até engrossar. O ponto deve ser igual brigadeiro, o mingau tem que começar a desgrudar da panela<br>Adoce se achar necessário<br>Está pronto! Sirva quente ou gelado.",
        cuisine: "brasileira",
        type_of: 1,
        image: "https://images.pexels.com/photos/19745775/pexels-photo-19745775/free-photo-of-placa-prato-saudavel-cafe-da-manha.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        ingredients: ["Aveia", "Leite", "Cacau em Pó"],
        difficulty: "fácil",
        restriction: ["gluten", "laticinio", "vegano"],
    },
    {
        name: "Chá gelado com limão",
        description: "Refrescante chá gelado com limão, a bebida perfeita para saciar a sede e revigorar os sentidos! Um copo gelado, preenchido com uma infusão refrescante de chá e o toque cítrico do limão fresco.<br><br>Ingredientes:<br>1/2 xícara de chá de açúcar<br>1 litro mais 1/2 xícara de chá de água<br>2 e 1/2 colheres de sopa de chá-mate<br>2 limões<br>Gelo a gosto<br><br>Modo de preparo:<br>Coloque o açúcar e meia xícara de chá de água em uma panela e leve ao fogo.<br>Misture bem e espere ferver.<br>Assim que o açúcar estiver totalmente dissolvido, desligue o fogo e espere esfriar.<br>Em uma chaleira, esquente o restante da água até quase ferver.<br>Desligue o fogo e adicione o chá.<br>Misture, tampe e deixe em infusão por 10 minutos.<br>Coe o chá e leve para gelar na geladeira.<br>Quando for servir, misture o xarope com o chá e adicione o suco dos limões.<br>Coloque gelo nos copos e sirva.",
        cuisine: "brasileira",
        type_of: 1,
        image: "https://images.pexels.com/photos/1484678/pexels-photo-1484678.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        ingredients: ["Chá", "Limão"],
        difficulty: "fácil",
        restriction: [],
    },
    {
        name: "Iogurte natural",
        description: "O iogurte natural caseiro é uma opção saudável e deliciosa que oferece uma maneira simples e econômica de desfrutar deste alimento probiótico. Com sua textura cremosa e sabor suave, o iogurte caseiro pode ser apreciado puro, com frutas ou utilizado em diversas receitas.<br><br>Ingredientes:<br>1 litro de leite<br>1 iogurte natural<br><br>Modo de preparo:<br>Ferva o leite, espere amornar, mas não deixe ficar frio.<br>Misture o iogurte junto ao leite morno, e coloque num recipiente médio ou grande (o equivalente a 1 litro) e deixe descansar de 12 a 24 horas.<br>De vez em quando mexa para ver como ficou a consistência.<br>Depois coloque na geladeira e sirva acompanhado com granola, quick de morango, ou algo de sua preferência. ",
        cuisine: "brasileira",
        type_of: 1,
        image: "https://images.pexels.com/photos/4736077/pexels-photo-4736077.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        ingredients: ["Leite", "Iogurte"],
        difficulty: "fácil",
        restriction: ["laticinio", "vegano"],
    },
    {
        name: "Geleia de morango",
        description: "Uma explosão de sabor doce e frutado em cada colherada! Um pote reluzente, repleto de morangos vermelhos e suculentos.<br><br>Ingredientes:<br>600 g de morango (2 caixinhas)<br>1 xícara (chá) de açúcar<br>1 colher (sobremesa) de suco de limão<br>5 cravos-da-índia (opcional)<br>1 colher (sobremesa) de amido de milho dissolvido em um pouquinho de água<br><br>Modo de preparo:<br>Colocar em uma panela o açúcar, depois os morangos com o suco de limão e os cravos-da-índia.<br>Levar ao fogo alto até ferver, depois fogo médio até o final, mexendo de vez em quando.<br>Cozinhar até que os morangos estejam molinhos, o que leva uns 15 minutos.<br>Passado esse tempo acrescente o amido de milho, mexa mais um pouco e desligue.",
        cuisine: "brasileira",
        type_of: 1,
        image: "https://images.pexels.com/photos/96580/pexels-photo-96580.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        ingredients: ["Morango", "Limão", "Amido de Milho"],
        difficulty: "fácil",
        restriction: ["gluten"],
    },
    {
        name: "Sequilhos de coco",
        description: "Biscoitinhos macios por dentro, levemente crocantes por fora, com o aroma irresistível e o sabor irresistível do coco fresco.<br><br>Ingredientes:<br>1 pacote de 500 g de amido de milho<br>200 g de manteiga em temperatura ambiente<br>1 1/2 xícaras de açúcar refinado<br>2 gemas<br>1/2 coco ralado<br>1 pitada de sal<br><br>Modo de preparo:<br>Em uma bacia grande coloque a maisena.<br>Acrescente a manteiga, o açúcar, as gemas, o coco ralado e o sal, amasse tudo com as mãos até que se unam e possam formar biscoitinhos, se não for possível formar os biscoitos, acrescente um pouco mais de maisena.<br>Pré-aqueça o forno em temperatura média e coloque os biscoitinhos em uma forma untada com manteiga.<br>Asse-os até que a parte de baixo do biscoito esteja dourada, mais ou menos 20 a 30 minutos, dependendo do forno.<br>Sirva com chá ou café, ficam super crocantes.",
        cuisine: "brasileira",
        type_of: 1,
        image: "https://images.pexels.com/photos/6970517/pexels-photo-6970517.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        ingredients: ["Manteiga", "Ovo", "Coco", "Amido de Milho"],
        difficulty: "fácil",
        restriction: ["gluten", "laticinio", "vegano"],
    },
    {
        name: "Bauru",
        description: "Uma combinação simplesmente irresistível de sabores! Ótimo para um café da manhã delicioso.<br><br>Ingredientes:<br>2 pacotes de pão de forma<br>4 colheres de maionese<br>1 lata de molho de tomate pronto<br>400 g de presunto<br>450 g de mussarela<br>Rodelas de tomate<br>Orégano<br><br>Modo de preparo:<br>Unte a forma com a maionese.<br>Coloque uma camada do pão de forma.<br>Em cima do pão coloque um pouco de molho de tomate (cubra todo o pão, mais cuidado para não colocar molho demais e não ficar enjoativo e mole).<br>Faça uma camada de presunto e outra de mussarela e coloque rodelas de tomate e o orégano por cima.<br>Coloque mais uma camada de pão de forma com o molho de tomate.<br>E mais uma camada de presunto, mussarela, tomate e orégano.<br>E por último, coloque mais uma camada de mussarela e orégano.<br>Leve ao formo por uns 15 minutos para que a mussarela derreta, cuidado pra não queimar o fundo.",
        cuisine: "brasileira",
        type_of: 1,
        image: "https://images.pexels.com/photos/19471395/pexels-photo-19471395/free-photo-of-sanduiche-cafe-da-manha-ovo-fruta.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        ingredients: ["Pão", "Maionese", "Presunto", "Molho de Tomate", "Tomate", "Queijo"],
        difficulty: "médio",
        restriction: ["gluten", "laticinio", "vegetariano", "vegano"],
    },
    {
        name: "Café com leite",
        description: "Essa receita é para você que gosta de um café com leite quentinho para sua manhã! Super simples e delicioso.<br><br>Ingredientes:<br>1 colher de sopa de café solúvel ou 1/4 de xícara de chá de café coado<br>1 xícara de chá de leite<br>1 colher de açúcar (opcional)<br><br>Modo de preparo:<br>Em uma panela adicione o leite, o café e o açúcar, misture bem.<br>Leve ao fogo baixo, mexendo sempre até ferver.<br>Cozinhe por mais 1 minuto e retire do fogo.<br>Sirva quente.",
        cuisine: "brasileira",
        type_of: 1,
        image: "https://images.pexels.com/photos/3278327/pexels-photo-3278327.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        ingredients: ["Café em Pó", "Leite"],
        difficulty: "fácil",
        restriction: ["laticinio", "vegano"],
    },
    {
        name: "Panqueca americana",
        description: "Panqueca americana deliciosa! Uma das comidas mais comuns no café da manhã dos Estados Unidos, ela é muito versátil e vai te proporcionar uma refeição muito especial!<br><br>Ingredientes:<br>1 e 1/4 xícara (chá) de farinha de trigo<br>1 colher (sopa) de açúcar<br>3 colheres (chá) de fermento em pó<br>2 ovos levemente batidos<br>1 xícara (chá) de leite<br>2 colheres (sopa) de manteiga derretida<br>Pitada de sal<br>Óleo<br><br>Modo de preparo:<br>Misture em um recipiente: a farinha, o açúcar, o fermento e o sal.<br>Em outro recipiente, misture os ovos, o leite e a manteiga.<br>Acrescente os líquidos aos secos, sem misturar em excesso.<br>O ponto da massa não deve ser muito líquido, deve escorrer lentamente.<br>Aqueça e unte a frigideira com óleo, coloque a massa no centro, cerca de 1/4 xícara por panqueca.<br>Vire a massa para assar do outro lado e está pronto!",
        cuisine: "americana",
        type_of: 1,
        image: "https://images.pexels.com/photos/10925937/pexels-photo-10925937.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        ingredients: ["Farinha", "Fermento", "Ovo", "Leite", "Manteiga", "Óleo"],
        difficulty: "médio",
        restriction: ["gluten", "laticinio", "vegano"],
    },
    {
        name: "Crepioca",
        description: "Uma opção deliciosa e saudável para suas refeições! Imagine uma panqueca macia e leve, feita com uma mistura especial de tapioca e ovos.<br><br>Ingredientes:<br>1 ovo<br>1 colher de tapioca<br>1 colher de requeijão<br>1 colher de água<br>1 pitada sal<br><br>Modo de preparo:<br>Bata todos os ingredientes em um liquidificador até obter uma consistência cremosa.<br>Despeje uma concha da massa numa frigideira levemente untada com margarina, tampe e deixe dourar. Recheie a gosto e dobre ao meio como um crepe.",
        cuisine: "brasileira",
        type_of: 1,
        image: "https://images.pexels.com/photos/6811030/pexels-photo-6811030.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        ingredients: ["Ovo", "Tapioca", "Requeijão"],
        difficulty: "fácil",
        restriction: ["laticinio", "vegano"],
    },
    {
        name: "Brusqueta",
        description: "Uma explosão de sabores em uma fatia de pão crocante! Imagine uma fatia generosa de pão rústico, levemente tostada, coberta com tomates frescos, alho e folhas de manjericão.<br><br>Ingredientes:<br>6 fatias de pão<br>10 tomates cereja ou fatias<br>200g de queijo mussarela ralado<br>Folhas de manjericão<br>Orégano a gosto<br>Sal a gosto<br>Óleo a gosto<br>Alho a gosto<br>Pimenta-do-reino (opcional) a gosto<br><br>Modo de preparo:<br>Corte as fatias do pão e coloque em uma forma (reserve).<br>Abra os tomates cereja ao meio e retire a semente e o líquido interno deixando ele limpo e seco.<br>Pique os tomates em cubos pequenos e coloque dentro de um recipiente.<br>Adicione uma pitada de sal, uma pitada de orégano e uma pitada de pimenta-do-reino (opcional).<br>Coloque óleo e misture.<br>Coloque 1 dente de alho do recipiente apenas para dar o gosto nos ingredientes e deixe descansar por 10 minutos.<br>Retire o dente de alho com uma colher e dispense.<br>Coloque os ingredientes sobre as fatias de pão.<br>Jogue por cima a mussarela e uma folha de manjericão para cada fatia de pão.<br>Já no forno bem quente, coloque a forma durante 3 minutos.<br>Retire e boa apetite!",
        cuisine: "italiana",
        type_of: 1,
        image: "https://images.pexels.com/photos/7655622/pexels-photo-7655622.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        ingredients: ["Pão", "Tomate", "Queijo", "Óleo", "Alho"],
        difficulty: "médio",
        restriction: ["gluten", "laticinio"],
    },
    {
        name: "Bolo de caneca",
        description: "Prepare-se para uma experiência rápida e deliciosa com este bolo de caneca de micro-ondas! Com apenas alguns minutos e uma caneca, você poderá desfrutar de um saboroso e reconfortante bolinho.<br><br>Ingredientes:<br>Massa:<br>1 ovo<br>2 colheres (sopa) de achocolatado em pó<br>3 colheres (sopa) rasas de açúcar<br>4 colheres (sopa) rasas de farinha de trigo<br>1 colher (sopa) de óleo<br>1 colher (café) rasa de fermento em pó<br>4 colheres (sopa) de leite<br><br>Calda:<br>2 colheres (sopa) de achocolatado em pó<br>1 colher (sopa) de manteiga<br>1/2 xícara de leite<br><br>Modo de preparo:<br>Coloque todos os ingredientes dentro de uma caneca de aproximadamente 300 ml ou mais.<br>Mexa até obter uma massa homogênea e leve ao microondas por 3 minutos.<br>Calda: Coloque todos os ingredientes em uma panela, leve ao fogo médio e misture até obter uma consistência grossa.<br>Despeje a calda sobre o bolo assim que retirá-lo do microondas.",
        cuisine: "brasileira",
        type_of: 1,
        image: "https://images.pexels.com/photos/12391466/pexels-photo-12391466.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        ingredients: ["Ovo", "Chocolate em Pó", "Farinha", "Óleo", "Fermento", "Leite", "Manteiga"],
        difficulty: "fácil",
        restriction: ["gluten", "laticinio", "vegano"],
    },
    {
        name: "Muffin",
        description: "Uma delícia macia e reconfortante que vai adoçar o seu dia! Imagine uma base fofinha e levemente úmida, repleta de sabores incríveis!<br><br>Ingredientes:<br>1/2 xícara de chá de açúcar<br>1/2 xícara de chá de chocolate em pó<br>1 xícara de farinha de trigo<br>2 ovos<br>4 colheres de sopa manteiga<br>150 ml de leite<br>1 colher de sopa de fermento em pó<br>Opcional: gotas de chocolate<br><br>Modo de preparo:<br>Junte em uma tigela o chocolate e a farinha (peneire-os) e separe.<br>Bata por uns 3 minutos na batedeira as gemas, o açúcar e a manteiga.<br>Adicione à batedeira a farinha com o chocolate e o leite alternando-os (coloque um pouco da farinha depois um pouco do leite e assim por diante).<br>Pare de bater e adicione o fermento em pó e as gotas de chocolate, misture delicadamente.<br>Bata as claras em neve e quando estiverem em ponto firme adicione a massa mexendo delicadamente a mão.<br>Unte as forminhas com manteiga e farinha.<br>Coloque a massa nas forminhas e leve ao forno pré-aquecido (180º graus) por mais ou menos 25 minutos.<br>Espete um palito para ver se estão sequinhos.<br>Espere esfriar um pouco e já pode servir.",
        cuisine: "inglesa",
        type_of: 1,
        image: "https://images.pexels.com/photos/4792398/pexels-photo-4792398.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        ingredients: ["Chocolate em Pó", "Farinha", "Ovo", "Manteiga", "Leite", "Fermento"],
        difficulty: "médio",
        restriction: ["gluten", "laticinio", "vegano"],
    },
]);
